config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get '/contact-us' => 'home#contact'
  get '/events' => 'home#events'
  get '/daily-darshan' => 'home#daily_darshan'
  get '/about-mandir' => 'home#about'
  mount Webmanager::Engine => "/webmanager"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper Webmanager::Engine.helpers


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index

  end

  def show
    @article = Webmanager::Article.find(params[:id])
    respond_to do |format|
      format.html { render :show, location: @article }
      format.json { render json: @article }
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Webmanager::Article.tagged_with('home')
    @subscriber = Webmanager::NewsletterReceiver.new
  end

  def daily_darshan

  end

  def about
    @about = Webmanager::Article.tagged_with('about').first
    @priest = Webmanager::Article.tagged_with('priest').first
  end

  def events
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @events = Webmanager::Event.where(:start_date => @date.beginning_of_month..@date.end_of_month)
    @events_by_date = @events.group_by(&:start_date)
  end

  def contact
    @contact = Webmanager::Form.where(name: 'Contact Form').first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/articles_helper.rb
module ArticlesHelper
  def find_by_tag(tag)
    @article = Webmanager::Article.tagged_with(tag)
  end
end

app/helpers/webmanager/calendar_helper.rb
module Webmanager
  module CalendarHelper

    def calendar(date = Date.today, &block)
      Calendar.new(self, date, block).table
    end

    class Calendar < Struct.new(:view, :date, :callback)
      HEADER = %w[S M T W T F S]
      START_DAY = :sunday
      delegate :content_tag, to: :view

      def table
        content_tag :table, class: 'table table-hover calendar mdl-data-table' do
          header + week_rows
        end
      end

      def header
        content_tag :thead do
          content_tag :tr do
            HEADER.map { |day| content_tag :th, day }.join.html_safe
          end
        end
      end

      def week_rows
        weeks.map do |week|
          content_tag :tr do
            week.map { |day| day_cell(day) }.join.html_safe
          end
        end.join.html_safe
      end

      def day_cell(day)
        content_tag :td, view.capture(day, &callback), class: day_classes(day)
      end

      def day_classes(day)
        classes= ['text-center']
        classes << 'today' if day == Date.today
        classes << 'notmonth' if day.month != date.month
        classes.empty? ? nil : classes.join(" ")
      end

      def weeks
        first = date.beginning_of_month.beginning_of_week(START_DAY)
        last = date.end_of_month.end_of_week(START_DAY)
        (first..last).to_a.in_groups_of(7)
      end
    end
  end
end

app/views/articles/show.html.erb
This is an article
<%= @article.inspect %>

app/views/home/about.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-no-padding">
  <%= image_tag('about-header.jpg') %>
</div>
<div class="container primary-font">
  <h3 class="text-center"><%= @about.title.titleize %></h3>
  <p><%= raw @about.body %></p>
  <hr>
  <div class="row align-items-center">
    <div class="col-sm-12  col-md-3">
      <img src="<%= @priest.blog_assets.first.asset.url(:medium) %>" class="col-12 rounded-circle"/>
    </div>
    <div class="col-sm-12 col-md-9">
      <h3><%= @priest.title.titleize %></h3>
      <p><%= raw @priest.body %></p>
    </div>
  </div>
  <p><small><em class="map-notice grey-text">Use <%= image_tag '/assets/map-drawer.svg', style:'height:16px;' %> icon on the map below to open the menu and see directions from various location to get to the temple.</em></small></p>
</div>
<%= render 'layouts/map' %>

app/views/home/contact.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-no-padding">
  <%= image_tag('contact-header.jpg') %>
</div>
<div class="container primary-font">
  <div class="col-12">
    <h3>Contact Us</h3>
    <p><%= @contact.description %></p>
    <%= form_for(Webmanager::FormResponse.new, url: '/webmanager/form_responses?method=post') do |f| %>
        <%= f.hidden_field :form_id, value: @contact.id %>
        <%= f.fields_for :response do |builder| %>
            <div class="form-group">
              <% @contact.form_fields.each do |contact_field| %>
                  <%= render "webmanager/form_fields/#{contact_field.as}", field: contact_field, f: builder %>
              <% end %>
            </div>
        <% end %>
        <div class="form-group">
          <%= submit_tag 'Submit', class: 'btn btn-primary' %>
        </div>
    <% end -%>
  </div>
  <div class="row">
    <div class="col-md-6">
      <p>Uttam Sloka Das (Head Priest)</p>
      <p>Phone: <a href="tel:+12402772010" itemprop="telephone">(240)277-2010</a></p>
    </div>
    <div class="col-md-6">
      <p>Rajesh Chokhani (COO Welspun Tubular LLC.)</p>
      <p>Phone: <a href="tel:+15015518995" itemprop="telephone">(501)551-8995</a></p>
    </div>
    <div class="col-md-6">
      <p>Mihir Desai (Supply Chain Manager Welspun Tubular LLC.)</p>
      <p>Phone: <a href="tel:+15015909877" itemprop="telephone">(501)590-9877</a></p>
    </div>
  </div>
  <p>
    <small>
      <em class="map-notice grey-text">Use <%= image_tag '/assets/map-drawer.svg', style: 'height:16px;' %> icon on the
        map below to open the menu and see directions from various location to get to the temple.</em></small>
  </p>
</div>
<%= render 'layouts/map' %>

app/views/home/daily_darshan.html.erb
<%= stylesheet_link_tag "/assets/social_wall/jquery.socialfeed.css", "/assets/social_wall/animate.css", media: 'all' %>
<%= javascript_include_tag "/assets/social_wall/doT.js", "/assets/social_wall/moment.js", "/assets/social_wall/jquery.socialfeed.js", "/assets/social_wall/twitter.widgets.js", "/assets/social_wall/masonry.pkgd.min.js", media: 'all' %>
<!--<div class="jumbotron jumbotron-fluid jumbotron-no-padding">-->
<!--<img src="https://placeimg.com/1446/400/nature "/>-->
<!--</div>-->
<div class="container primary-font" style="margin-top: 65px !important;">
  <div class="col-sm-12">
    <section id="social-medial-wall" class="feed padding-lg">
      <div class="container">
        <div class="social-feed-container padding-md grid row align-items-stretch" id="social-feed-container">
        </div>
      </div>
    </section>
  </div>
</div>


<script>
  $(document).ready(function () {

    var updateFeed = function () {
      $('.social-feed-container').socialfeed({
        // FACEBOOK
        facebook: {
//          accounts: ['@TheEdgeAtDonaghey'],
          accounts: ['@TheRadhamadhavTemple'],
          limit: 12,
//          access_token: '246932055646003|07ada32da2c81d2a08fa43e00ff6766a',
          access_token: '744967052342034|57ee98b5e27d61f4554b3736e5f246b1',
          show_media: true
        },
        // GENERAL SETTINGS
        length: 1000,
        date_format: "ll",                              //String: Display format of the date attribute (see http://momentjs.com/docs/#/displaying/format/)
        date_locale: "en",                              //String: The locale of the date (see: http://momentjs.com/docs/#/i18n/changing-locale/)
        media_min_width: 50,
        // Moderation function - if returns false, template will have class hidden
        moderation: function (content) {
          return (content.text) ? content.text.indexOf('fuck') == -1 : true;
        },
//        update_period: 5000,
        template: '',
        template_html:                                  //String: HTML used for each post. This overrides the 'template' filename option
            '<div class="social-feed-item {{? !it.moderation_passed}}hidden{{?}} col-md-3 col-sm-6 col-12 no-margin" dt-create="{{=it.dt_create}}" social-feed-id = "{{=it.id}}">\
              <div class="social-feed-element">\
                {{? it.attachment}}\
                <a target="_blank" href="{{=it.link}}">\
                  {{=it.attachment}}\
                </a>\
                {{?}} \
                <div class="content">\
                  <div class="media-body">\
                    <div class="text-wrapper">\
                      <div class="social-feed-text facebook">\
                        {{=it.text}}\
                        <ul class="facebook-links list-inline">\
                          <li><a target="_blank" href="https://twitter.com/intent/tweet?text={{=it.original_text}}&url={{=it.link}}&via="><i class="fa fa-twitter-square"></i></a></li>\
                          <li><a target="_blank" href="https://plus.google.com/share?url={{=it.link}}"><i class="fa fa-google-plus-square"></i></a></li>\
                        </ul>\
                      </div>\
                    </div>\
                  </div>\
                </div>\
              </div>\
                <div class="media-footer">\
                  <div class="{{=it.social_network}} social-network">\
                    <i class="fa fa-{{=it.social_network}} icon"></i>\
                    <span>\
                      {{=it.author_name}} posted {{=it.date}}\
                    </span>\
                  </div>\
                </div>\
              </div>\
            </div>',
        // When all the posts are collected and displayed - this function is evoked
        callback: function () {
          console.log('all posts are collected');
          $('#social-medial-wall').show(0);
//          $('#social-feed-container .grid-item').addClass('animated zoomIn');
//          $('#social-feed-container').masonry({
//            // options
//            itemSelector: '.grid-item',
//          });

        }
      });
    };

    updateFeed();


  });
</script>

app/views/home/events.html.erb
<div class="container primary-font" style="margin-top: 65px !important;">
  <div class="card col-lg-8 offset-lg-2">
    <div class="card-block">
      <h4 class="card-title text-center">
        <%= link_to '<i class="material-icons">chevron_left</i>'.html_safe, date: @date.prev_month %>
        <%= @date.strftime("%B %Y") %>
        <%= link_to '<i class="material-icons">chevron_right</i>'.html_safe, date: @date.next_month %>
      </h4>
      <p class="card-text">
        <%= calendar @date do |date| %>
            <% if @events_by_date[date] %>
            <%= date.day %><span class="badge badge-pill badge-success event-notification"><%= @events_by_date[date].count %></span>
            <% else %>
            <%= date.day %>
            <% end %>
        <% end %>
      </p>
    </div>
  </div>

  <h2>Upcoming Events</h2>
  <% if !@events.empty? %>
      <div id="accordion" role="tablist" aria-multiselectable="true">
        <% @events.each do |event| %>
            <% id = "#{event.name.downcase.gsub(' ', '_').gsub('(','').gsub(')','')}_#{event.id}" %>
            <% id_top = "#{event.name.downcase.gsub(' ', '_').gsub('(','').gsub(')','')}" %>
            <div class="card events-card">
              <div class="card-header" role="tab" id="<%= id_top %>">
                <h5 class="mb-0 col-12">
                  <a data-toggle="collapse" data-parent="#accordion" href="#<%= id %>" aria-expanded="<%= (event.id == 1) ? true : false %>" aria-controls="<%= id %>">
                    <%= event.name %>
                  </a>
                </h5>
              </div>

              <div id="<%= id %>" class="collapse" role="tabpanel" aria-labelledby="<%= id_top %>">
                <div class="card-block">
                  <div class="clearfix">
                    <p class="float-left"><i class="material-icons">place</i><%= event.location %></p>
                    <p class="float-right">
                      <i class="material-icons">event</i><%= event.start_date.to_date.to_formatted_s(:long) %> <%= "– #{event.end_date.to_date.to_formatted_s(:long)}" if event.end_date %>
                    </p>
                  </div>
                  <p><%= event.description %></p>
                </div>
              </div>
            </div>
        <% end %>
      </div>
  <% else %>
      <p>No events scheduled for this month yet, please check back later.</p>
  <% end %>
</div>

app/views/home/index.html.erb
<%= render 'layouts/carousel' %>

<div class="container primary-font">
  <% @articles.each do |article| %>
      <h3 class="text-center"><%= article.title.titleize %></h3>
      <div class="row align-items-center">
        <% if article.blog_assets.any? %>
            <div class="col-sm-12 col-md-6">
              <%= image_tag article.blog_assets.first.asset.url(:medium), class: 'responsive-img' %>
            </div>
        <% end %>
        <div class="col-sm-12 col-md-6">
          <%= raw article.body %>
        </div>
      </div>
  <% end %>
</div>

app/views/layouts/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <% @assets = Webmanager::BlogAsset.all %>
  <% if @assets.present? %>
      <ol class="carousel-indicators">
        <% @assets.each_with_index do |asset, index| %>
            <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="<%= (index == 0) ? 'active' : nil %>"></li>
        <% end %>
      </ol>
      <div class="carousel-inner" role="listbox">
        <% @assets.each_with_index do |asset, index| %>
            <div class="carousel-item <%= (index == 0) ? 'active' : nil %>" style="background-image:url('<%= asset.asset.url %>')">
            </div>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row align-items-end">
      <div class="col-md-12 col-lg-6">
        <%= image_tag 'welspun-logo.jpg', class: 'rounded mx-auto d-block', style: 'width: 50%;' %>
        <div itemscope itemtype="http://schema.org/ContactPoint">
          <p><h5 class="text-center">Shri Radha Madhav Temple</h5></p>
          <p class="float-left">Phone: <a href="tel:+12402772010" itemprop="telephone">(240)277-2010</a></p>
          <p class="float-right"> Email:
            <a href="mailto:welspuntemple@gmail.com" itemprop="email">welspuntemple@gmail.com</a></p>
          <p class="float-left" itemscope itemtype="schema.org/PostalAddress"> Address:
            <span itemprop="streetAddress">9301 Frazier Pike</span>,
            <span itemprop="addressLocality">Little Rock</span>
            <span itemprop="postalCode">AR-72206</span>
          </p>
        </div>
      </div>
      <div class="col-md-12 col-lg-6">
        <%= form_for(Webmanager::NewsletterReceiver.new, url: 'webmanager/newsletter_receivers', method: 'post') do |f| %>
            <%= f.label :email, 'Sign up for an events newsletter: ' %>
            <%= f.text_field :email, placeholder: "Type your email to get notified",  class: 'form-control' %>
            <%= f.hidden_field :event_notification, value: true %>
            <%= f.submit 'Subscribe', class:'btn btn-primary' %>
        <% end %>
        <p>&copy; <%= Time.current.year %> Radha Madhav Temple &middot; <a href="#">Privacy</a> &middot;
          <a href="#">Terms</a>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_map.html.erb
<div class="row map">
  <div class="container">
    <div class="col-12">
      <iframe src="https://www.google.com/maps/d/u/3/embed?mid=10WURbW4N1A9R9lECVZ-t2VdoZDI" class="col-12" height="400px" id="map_frame"></iframe>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'Radha Madhav Temple', root_path, class:'navbar-brand' %>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item <%= 'active' if params[:action]=='index' %>">
        <%= link_to 'Home', root_path, class:'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if params[:action]=='daily_darshan' %>">
        <%= link_to 'Daily Darshan', daily_darshan_path, class:'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if params[:action]=='events' %>">
        <%= link_to 'Events', events_path, class:'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if params[:action]=='about' %>">
        <%= link_to 'About Temple', about_mandir_path, class:'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if params[:action]=='contact' %>">
        <%= link_to 'Contact', contact_us_path, class:'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_slider.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
      <div class="container">
        <div class="carousel-caption d-none d-md-block text-left">
          <h1>Example headline.</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
      <div class="container">
        <div class="carousel-caption d-none d-md-block">
          <h1>Another example headline.</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
      <div class="container">
        <div class="carousel-caption d-none d-md-block text-right">
          <h1>One more for good measure.</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
        </div>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <title>Radhamadhav</title>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= raw google_analytics(123) %>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <%= stylesheet_link_tag 'application', 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/navigation' %>
<div class="content">
  <% if notice.present? %>
      <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
      <p class="alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>